services:
  jenkins:
    build: .
    image: custom-jenkins:lts
    container_name: jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # enable docker inside Jenkins

volumes:
  jenkins_home:
